security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_admin
        always_use_default_target_path: true
        failure_path: app_login
      logout:
        path: app_logout
        target: app_home

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
