framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.filesystem
        
        pools:
            cache.validator:
                adapter: cache.adapter.filesystem
            cache.serializer:
                adapter: cache.adapter.filesystem
            cache.annotations:
                adapter: cache.adapter.filesystem
            cache.property_info:
                adapter: cache.adapter.filesystem
            cache.messenger.restart_workers_signal:
                adapter: cache.adapter.filesystem
            cache.validator_expression_language:
                adapter: cache.adapter.filesystem
            cache.security_expression_language:
                adapter: cache.adapter.filesystem
            cache.security_is_csrf_token_valid_attribute_expression_language:
                adapter: cache.adapter.filesystem
            cache.doctrine.orm.default.result:
                adapter: cache.adapter.filesystem
            cache.doctrine.orm.default.query:
                adapter: cache.adapter.filesystem
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
            cache.asset_mapper:
                adapter: cache.adapter.filesystem
            recipes.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
            search.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 1800
            static.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 7200
            images.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 604800