framework:
  messenger:
    failure_transport: failed

    transports:
      sync: "sync://"
      failed: "doctrine://default?queue_name=failed"

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: []

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
