controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_recipe_search:
  path: /recherche
  controller: App\Controller\RecipeController::search

app_mentions_legales:
  path: /mentions-legales
  controller: App\Controller\DefaultController::mentionsLegales
